# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="The Haskell Tool Stack"
HOMEPAGE="http://haskellstack.org"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="disable-git-info hide-dependency-versions integration-tests static"

RDEPEND="dev-haskell/annotated-wl-pprint:=[profile?]
	>=dev-haskell/ansi-terminal-0.6.2.3:=[profile?]
	>=dev-haskell/async-2.0.2:=[profile?] <dev-haskell/async-2.2:=[profile?]
	>=dev-haskell/attoparsec-0.12.1.5:=[profile?] <dev-haskell/attoparsec-0.14:=[profile?]
	>=dev-haskell/base-compat-0.6:=[profile?] <dev-haskell/base-compat-0.10:=[profile?]
	dev-haskell/base16-bytestring:=[profile?]
	dev-haskell/base64-bytestring:=[profile?]
	>=dev-haskell/binary-0.7:=[profile?] <dev-haskell/binary-0.9:=[profile?]
	>=dev-haskell/binary-tagged-0.1.1:=[profile?]
	dev-haskell/blaze-builder:=[profile?]
	dev-haskell/byteable:=[profile?]
	>=dev-haskell/cabal-1.18.1.5:=[profile?] <dev-haskell/cabal-1.25:=[profile?]
	>=dev-haskell/clock-0.7.2:=[profile?]
	>=dev-haskell/conduit-1.2.4:=[profile?]
	>=dev-haskell/conduit-extra-1.1.7.1:=[profile?]
	>=dev-haskell/cryptohash-0.11.6:=[profile?]
	dev-haskell/cryptohash-conduit:=[profile?]
	>=dev-haskell/edit-distance-0.2:=[profile?]
	dev-haskell/either:=[profile?]
	dev-haskell/enclosed-exceptions:=[profile?]
	<dev-haskell/errors-2.2:=[profile?]
	>=dev-haskell/exceptions-0.8.0.2:=[profile?]
	<dev-haskell/extra-1.6:=[profile?]
	>=dev-haskell/fast-logger-2.3.1:=[profile?]
	>=dev-haskell/filelock-0.1.0.1:=[profile?]
	>=dev-haskell/fsnotify-0.2.1:=[profile?]
	<dev-haskell/generic-deriving-1.12:=[profile?]
	>=dev-haskell/hashable-1.2.3.2:=[profile?]
	dev-haskell/hastache:=[profile?]
	dev-haskell/hit:=[profile?]
	>=dev-haskell/hpack-0.14.0:=[profile?] <dev-haskell/hpack-0.16:=[profile?]
	>=dev-haskell/http-client-0.5.0:=[profile?]
	>=dev-haskell/http-client-tls-0.3.0:=[profile?]
	>=dev-haskell/http-conduit-2.2.0:=[profile?]
	>=dev-haskell/http-types-0.8.6:=[profile?] <dev-haskell/http-types-0.10:=[profile?]
	dev-haskell/lifted-async:=[profile?]
	>=dev-haskell/microlens-0.3.0.0:=[profile?]
	dev-haskell/monad-control:=[profile?]
	>=dev-haskell/monad-logger-0.3.13.1:=[profile?]
	<dev-haskell/monad-unlift-0.3:=[profile?]
	>=dev-haskell/mtl-2.1.3.1:=[profile?]
	>=dev-haskell/open-browser-0.2.1:=[profile?]
	>=dev-haskell/optparse-applicative-0.13:=[profile?] <dev-haskell/optparse-applicative-0.14:=[profile?]
	>=dev-haskell/path-0.5.8:=[profile?]
	>=dev-haskell/path-io-1.1.0:=[profile?] <dev-haskell/path-io-2.0.0:=[profile?]
	>=dev-haskell/persistent-2.1.2:=[profile?] <dev-haskell/persistent-2.7:=[profile?]
	>=dev-haskell/persistent-template-2.1.1:=[profile?] <dev-haskell/persistent-template-2.6:=[profile?]
	>=dev-haskell/project-template-0.2:=[profile?]
	>=dev-haskell/regex-applicative-text-0.1.0.1:=[profile?] <dev-haskell/regex-applicative-text-0.2:=[profile?]
	>=dev-haskell/resourcet-1.1.4.1:=[profile?]
	>=dev-haskell/retry-0.6:=[profile?] <dev-haskell/retry-0.8:=[profile?]
	>=dev-haskell/safe-0.3:=[profile?]
	>=dev-haskell/semigroups-0.5:=[profile?] <dev-haskell/semigroups-0.19:=[profile?]
	dev-haskell/split:=[profile?]
	>=dev-haskell/stm-2.4.4:=[profile?]
	>=dev-haskell/store-0.2.1.0:=[profile?]
	>=dev-haskell/streaming-commons-0.1.10.0:=[profile?]
	>=dev-haskell/tar-0.5.0.3:=[profile?] <dev-haskell/tar-0.6:=[profile?]
	>=dev-haskell/temporary-1.2.0.3:=[profile?]
	>=dev-haskell/text-1.2.0.4:=[profile?]
	dev-haskell/text-binary:=[profile?]
	>=dev-haskell/tls-1.3.8:=[profile?]
	>=dev-haskell/transformers-0.3.0.0:=[profile?] <dev-haskell/transformers-0.6:=[profile?]
	>=dev-haskell/transformers-base-0.4.4:=[profile?]
	>=dev-haskell/unicode-transforms-0.1:=[profile?] <dev-haskell/unicode-transforms-0.2:=[profile?]
	dev-haskell/unix-compat:=[profile?]
	>=dev-haskell/unordered-containers-0.2.5.1:=[profile?]
	>=dev-haskell/vector-0.10.12.3:=[profile?] <dev-haskell/vector-0.12:=[profile?]
	dev-haskell/vector-binary-instances:=[profile?]
	>=dev-haskell/yaml-0.8.10.1:=[profile?]
	<dev-haskell/zip-archive-0.4:=[profile?]
	>=dev-haskell/zlib-0.5.4.2:=[profile?] <dev-haskell/zlib-0.7:=[profile?]
	>=dev-lang/ghc-7.10.1:=
	|| ( ( >=dev-haskell/aeson-0.8.0.2:=[profile?] <dev-haskell/aeson-0.10:=[profile?] )
		( >=dev-haskell/aeson-0.11:=[profile?] <dev-haskell/aeson-0.12:=[profile?] ) )
	|| ( <dev-haskell/lifted-base-0.2.3.7:=[profile?]
		>dev-haskell/lifted-base-0.2.3.7:=[profile?] )
	|| ( ( >=dev-haskell/persistent-sqlite-2.1.4:=[profile?] <dev-haskell/persistent-sqlite-2.5.0.1:=[profile?] )
		( >dev-haskell/persistent-sqlite-2.5.0.1:=[profile?] <dev-haskell/persistent-sqlite-2.7:=[profile?] ) )
	!disable-git-info? ( >=dev-haskell/gitrev-1.1:=[profile?] <dev-haskell/gitrev-1.3:=[profile?]
				>=dev-haskell/optparse-simple-0.0.3:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
	test? ( >=dev-haskell/hspec-2.2 <dev-haskell/hspec-2.3
		dev-haskell/mono-traversable
		>=dev-haskell/neat-interpolation-0.3
		<dev-haskell/quickcheck-2.10
		dev-haskell/smallcheck
		dev-haskell/th-reify-many )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag disable-git-info disable-git-info) \
		$(cabal_flag hide-dependency-versions hide-dependency-versions) \
		$(cabal_flag integration-tests integration-tests) \
		$(cabal_flag static static)
}
